from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from config import settings
from services import session_store

logger = logging.getLogger(__name__)

router = APIRouter()


@router.get("/sessions/{session_id}/metrics")
async def get_metrics(session_id: str) -> dict[str, Any]:
    """
    Return the full metrics JSON for a completed session.

    - 202 if the pipeline is still running
    - 404 if the session does not exist or metrics.json is missing
    - 200 with the metrics dict if status == 'done'
    """
    session = session_store.get_session(session_id)
    if session is None:
        raise HTTPException(status_code=404, detail=f"Sessão '{session_id}' não encontrada")

    status: str = session.get("status", "")

    if status == "processing":
        raise HTTPException(
            status_code=202,
            detail="O pipeline ainda está em execução. Tente novamente em instantes.",
        )

    if status != "done":
        raise HTTPException(
            status_code=404,
            detail=(
                f"Métricas não disponíveis. Status atual da sessão: '{status}'. "
                "Processe o vídeo primeiro."
            ),
        )

    metrics_path: Path = settings.sessions_dir / session_id / "metrics.json"
    if not metrics_path.exists():
        raise HTTPException(
            status_code=404,
            detail="Arquivo de métricas não encontrado. O pipeline pode ter falhado.",
        )

    try:
        metrics: dict[str, Any] = json.loads(metrics_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        logger.error("Erro ao ler metrics.json para sessão %s: %s", session_id, exc)
        raise HTTPException(status_code=500, detail="Erro ao ler arquivo de métricas") from exc

    return metrics


@router.get("/sessions/{session_id}/heatmap.png")
async def get_heatmap(session_id: str) -> FileResponse:
    """Return the heatmap PNG generated by the pipeline."""
    session = session_store.get_session(session_id)
    if session is None:
        raise HTTPException(status_code=404, detail=f"Sessão '{session_id}' não encontrada")

    heatmap_path: Path = settings.sessions_dir / session_id / "heatmap.png"
    if not heatmap_path.exists():
        raise HTTPException(
            status_code=404,
            detail="Heatmap não encontrado. Processe o vídeo primeiro.",
        )

    return FileResponse(
        path=str(heatmap_path),
        media_type="image/png",
        filename=f"heatmap_{session_id}.png",
    )
